language: c

branches:
  only:
    - master
    # release branches
    - /^[0-9]+\.[0-9]+$/
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

dist: bionic

addons:
  # linux dependencies
  apt:
    packages:
      - wget
      - tar
      - gzip
      - make
      - autoconf
      - automake
      - libtool
    update: true

matrix:
  include:
    - os: linux
      arch: arm64
      compiler: gcc
      env: CC=gcc LSSL_VERSION=3.1.3
    - os: linux
      arch: ppc64le
      compiler: gcc
      env: CC=gcc LSSL_VERSION=3.1.3
    - os: linux
      arch: amd64
      compiler: gcc
      env: CC=gcc LSSL_VERSION=3.1.3
    - os: linux
      arch: arm64
      compiler: clang
      env: CC=clang LSSL_VERSION=3.1.3
    - os: linux
      arch: ppc64le
      compiler: clang
      env: CC=clang LSSL_VERSION=3.1.3
    - os: linux
      arch: amd64
      compiler: clang
      env: CC=clang LSSL_VERSION=3.1.3

before_install:
  - |
      LSSL_NAME="libressl-${LSSL_VERSION}.tar.gz"
      LSSL_URL="http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/${LSSL_NAME}"
      mkdir -p distfiles
      if [ ! -f "./distfiles/${LSSL_NAME}" ]; then
          wget -O ./distfiles/${LSSL_NAME} ${LSSL_URL}
      fi

cache:
  directories:
    - $TRAVIS_BUILD_DIR/distfiles/

script:
  - tar xzf distfiles/libressl-${LSSL_VERSION}.tar.gz
  - ./patch_libressl.sh libressl-${LSSL_VERSION}
  - cd libressl-${LSSL_VERSION}
  - autoreconf -if
  - mkdir build && cd build
  - ../configure
  - make -j3 check V=1
